// Runs after test:e2e; uses a COPY of its synthetic project and real local APIs.
import assert from 'node:assert/strict';
import {readFile, writeFile, mkdir, cp, rename} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {chromium} from 'playwright';
import {startServer} from '../../src/server.js';
import {sha256} from '../../src/core/store.js';
const studio = fileURLToPath(new URL('../../', import.meta.url));
const out = path.join(studio, '.test-output/integration-r4');
const baseline = JSON.parse(await readFile(path.join(studio, '.test-output/acceptance/acceptance.json')));
assert.equal(baseline.passed, true);
const id = baseline.projectId;
const root = path.join(out, 'projects');
await mkdir(root, {recursive:true});
await cp(baseline.projectDir, path.join(root,id), {recursive:true});
let app = await startServer({port:0,root});
let browser;
const evidence = {projectId:id, checks:[], errors:[], unexpectedConsoleErrors:[]};
const check = name => evidence.checks.push(name);
let expectedFailure = false;
try {
 browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1500,height:1000}});
 page.on('pageerror', e => evidence.errors.push(e.message));
 page.on('console', e => {if(e.type()==='error' && !expectedFailure) evidence.unexpectedConsoleErrors.push(e.text());});
 const screenshot = async name => page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
 const open = async () => {
  await page.goto(app.url);
  await page.locator(`[data-project="${id}"]`).click();
  await page.waitForFunction(() => document.querySelector('#source-video').readyState>=2);
 };
 await page.goto(app.url);
 await screenshot('intake');
 await open();
 await page.locator('#seek').fill(String(1500));
 await page.locator('#seek').dispatchEvent('input');
 await page.waitForFunction(() => document.querySelector('#source-video').currentTime>=1.4);
 await screenshot('editor-landscape');
 await page.locator('#vertical-preview').click();
 assert.match(await page.locator('#preview-truth').innerText(),/crops and reframes around your saved focus without stretching/);
 assert.doesNotMatch(await page.locator('#preview-truth').innerText(),/keeps that wide picture/);
 await screenshot('editor-portrait');
 await page.locator('#finish-split').click();
 await page.waitForFunction(() => {const video=document.querySelector('#compare-video'); return video.readyState>=2 && !video.seeking;});
 assert.equal(await page.locator('#compare-video').evaluate(video => video.error),null);
 await screenshot('editor-split');
 await page.locator('#finish-raw').click();
 assert.equal(await page.locator('#picture').evaluate(e => e.style.transform),'none');
 await screenshot('editor-raw');
 await page.locator('#finish-draft').click();
 await page.locator('#landscape-preview').click();
 await page.locator('#captions-section summary').click();
 assert.equal(await page.locator('[data-text]').inputValue(),'Prepare your next campaign in one click.');
 await screenshot('captions');
 check('landscape/portrait/raw/split drafts and saved caption controls; truthful crop warning');
 await page.locator('#exports-tab').click();
 assert.match(await page.locator('#export-receipt').innerText(),/focus-based portrait crop/);
 assert.doesNotMatch(await page.locator('#export-receipt').innerText(),/wide picture kept|separate render lane/);
 for (const file of ['landscape.mp4','vertical.mp4','captions.srt','captions.vtt','portrait.html','vertical-thumbnail.png']) {
  assert.equal(await page.locator(`#export-list a[href$="/${file}"]`).count(),1);
 }
 await screenshot('export-receipt');
 check('R3 SRT/VTT, portrait share/thumbnail and both movies exposed in receipt');
 await page.setViewportSize({width:390,height:844});
 const mobileFit = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth),true);
 await mobileFit(); await screenshot('mobile-exports');
 await page.locator('#editor-tab').click();
 await mobileFit();
 assert.equal(await page.locator('#timeline-ruler span').count(),5);
 assert.equal(await page.locator('#timeline-ruler span').evaluateAll(items => items.every((item,i) => i===0 || items[i-1].getBoundingClientRect().right<=item.getBoundingClientRect().left)),true);
 await screenshot('mobile-editor');
 await page.locator('#vertical-preview').click();
 await mobileFit(); await screenshot('mobile-portrait');
 await page.locator('#new-project').click();
 await mobileFit(); await screenshot('mobile-intake-dialog');
 await page.locator('#close-dialog').click();
 check('390px editor, portrait preview, exports and intake dialog without horizontal overflow');
 await page.setViewportSize({width:1500,height:1000});
 await page.locator('#landscape-preview').click();
 // Stale receipt must describe the current settings as such, not as rendered facts.
 await page.locator('#title').fill('R4 receipt recovery');
 await page.locator('#zoom').fill('1.5');
 await page.locator('#zoom').dispatchEvent('input');
 await page.locator('#save').click();
 await page.waitForFunction(() => document.querySelector('#saved-state').textContent==='Saved locally');
 await page.locator('#exports-tab').click();
 assert.match(await page.locator('.receipt-warn').innerText(),/Settings below describe the current saved timeline, not those files/);
 assert.ok(await page.locator('.export-card.stale').count()>0);
 await screenshot('stale-receipt');
 check('saved edits mark files stale and do not misrepresent old files as current settings');
 // A real server error, induced only in the copied test project. Preserve old exports.
 const project = await app.store.get(id);
 const original = path.join(app.store.dir(id),project.studio.asset.path);
 const hidden = original+'.r4-test-hidden';
 const before = await sha256(path.join(app.store.dir(id),'exports/landscape.mp4'));
 expectedFailure=true;
 await rename(original,hidden);
 try {
  await page.locator('#render').click();
  await page.locator('#progress-panel.failed').waitFor({state:'visible',timeout:20000});
  assert.match(await page.locator('#progress-message').innerText(),/missing|ENOENT|Original/i);
  await screenshot('render-failure');
  assert.equal(await sha256(path.join(app.store.dir(id),'exports/landscape.mp4')),before);
 } finally {await rename(hidden,original);}
 await page.locator('#dismiss-progress').click();
 await page.locator('#dismiss-notification').click();
 expectedFailure=false;
 check('real missing-original render error visible/dismissible; previous export hash unchanged');
 await page.locator('#editor-tab').click();
 await page.locator('#render').click();
 await page.locator('#progress-panel:not(.hidden)').waitFor({state:'visible'});
 await screenshot('render-progress');
 await page.waitForFunction(() => !document.querySelector('#exports-view').classList.contains('hidden') && document.querySelector('#progress-panel').classList.contains('hidden'),{}, {timeout:240000});
 assert.equal(await page.locator('.export-card.stale').count(),0);
 assert.equal(await page.locator('.receipt-warn').count(),0);
 await screenshot('recovered-receipt');
 check('retry after restoring original renders successfully, clears stale state and exposes final receipt');
 await page.locator('#editor-tab').click();
 const current = await app.store.get(id);
 await new Promise(r=>app.server.close(r));
 app = await startServer({port:0,root});
 await open();
 assert.equal(await page.locator('#title').inputValue(),'R4 receipt recovery');
 assert.equal(await page.locator('#zoom').inputValue(),'1.5');
 assert.deepEqual((await app.store.verify(id)).timeline,current.timeline);
 assert.equal(await sha256(original),baseline.sourceHash);
 await screenshot('reopened-editor');
 check('actual server restart and browser reopen preserve saved edits, captions, original hash and export links');
 assert.deepEqual(evidence.errors,[]);
 assert.deepEqual(evidence.unexpectedConsoleErrors,[]);
 evidence.passed=true;
} finally {
 await browser?.close();
 await new Promise(r=>app.server.close(r));
 await writeFile(path.join(out,'ui-acceptance.json'),JSON.stringify(evidence,null,2)+'\n');
}
console.log(JSON.stringify(evidence,null,2));
