const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={AWARENESS:'Awareness',WEBSITE_TRAFFIC:'Website traffic',LEADS:'Leads',SALES:'Sales',LOCAL_APPOINTMENTS:'Local appointments',META:'Meta',GOOGLE_ADS:'Google Ads',CHATGPT_ADS:'ChatGPT Ads · availability dependent',ORGANIC_ONLY:'Organic only',NONE:'None',UNKNOWN:'Unknown',YES:'Yes',NO:'No'};
const badge=label=>`<span class="provenance ${label.toLowerCase()}">${esc(label.replaceAll('_',' '))}</span>`;
const cash=c=>`$${(c/100).toFixed(2)}`;
export function growthPlanView(project,fileUrl) {
 const p=project.growthPlan,i=p?.input||{businessName:project.name,url:project.url,totalBudget:100,days:7,goal:'LEADS',primaryChannel:'META',currency:'USD',specialCategory:'UNKNOWN'};
 const field=(name,label,opts='')=>`<label>${label}<input name="${name}" value="${esc(i[name]??'')}" ${opts}></label>`;
 const select=(name,label,values)=>`<label>${label}<select name="${name}">${values.map(v=>`<option value="${v}" ${v===(i[name]??'UNKNOWN')?'selected':''}>${names[v]||v.replaceAll('_',' ')}</option>`).join('')}</select></label>`;
 const text=(name,label,max=1000)=>`<label>${label}<textarea name="${name}" maxlength="${max}" rows="2">${esc(i[name]||'')}</textarea></label>`;
 return `<div class="section-title"><div><div class="eyebrow">Growth plan / evidence into action</div><h2>Make a small budget deliberate.</h2></div><span class="badge hold">Ad platforms · NOT CONNECTED</span></div><p class="lede-note">One objective, a clear spending envelope, and useful organic work. Plan locally without an ad account or payment. Save a plan, review its assumptions, then bring it into Campaign. External ad execution is not connected.</p>
 <div class="planner-layout"><form id="growth-plan-form" class="planner-form"><div class="planner-fields">
 ${field('businessName','Business name','required maxlength="64"')}${field('category','Business category','required maxlength="120" placeholder="e.g. Local bakery"')}
 ${field('geography','Geography','required maxlength="160" placeholder="e.g. Portland, Oregon"')}${field('audience','Audience','required maxlength="240" placeholder="Describe the people you serve"')}
 ${field('totalBudget','Total budget · USD','type="number" min="0" max="1000000" step="0.01" required')}${field('days','Duration · days','type="number" min="1" max="365" step="1" required')}
 ${select('goal','Business goal',['LEADS','SALES','LOCAL_APPOINTMENTS','WEBSITE_TRAFFIC','AWARENESS'])}${select('primaryChannel','Primary paid channel',['META','GOOGLE_ADS','CHATGPT_ADS','ORGANIC_ONLY'])}
 </div><details class="fold"><summary>Destination, offer and evidence</summary>${field('url','Business URL · optional','type="url" maxlength="2048"')}${field('landingPage','Relevant landing page · optional','type="url" maxlength="2048"')}${text('offer','Offer · facts you can substantiate',240)}${text('assets','Existing creative assets · describe what you own')}${text('organicEvidence','Existing organic / AI evidence · user notes, not verified',2000)}</details>
 <details class="fold" ${p?.warnings.some(w=>w.includes('CATEGORY'))?'open':''}><summary>Audience and category review</summary><div class="planner-fields">${select('remarketingAudience','Usable remarketing audience',['UNKNOWN','NO','YES'])}${select('customerList','Usable customer list',['UNKNOWN','NO','YES'])}${select('specialCategory','Special ad category',['UNKNOWN','NONE','HOUSING','EMPLOYMENT','FINANCIAL_PRODUCTS_SERVICES','POLITICAL_SOCIAL_ISSUES'])}${select('chatgptAvailability','ChatGPT Ads availability known',['UNKNOWN','NO','YES'])}</div><label class="check"><input type="checkbox" name="retargetingRequested" ${i.retargetingRequested?'checked':''}> Consider retargeting if the budget and usable audience support it</label><p class="muted">A category selection is your input. Review applicable platform rules; this planner does not establish eligibility.</p></details>
 <details class="fold"><summary>Optional economics · scenarios, never forecasts</summary><div class="planner-fields">${field('averageOrderValue','Average order value · USD','type="number" min="0" max="1000000" step="0.01"')}${field('leadValue','Estimated lead value · USD','type="number" min="0" max="1000000" step="0.01"')}${field('conversionRate','Conversion rate · %','type="number" min="0" max="100" step="0.01"')}${field('contributionMargin','Contribution margin · %','type="number" min="0" max="100" step="0.01"')}</div><p class="muted">Revenue is not profit. Without contribution margin, no break-even CPA or ROAS is calculated.</p></details>
 <div class="button-row"><button type="submit" class="primary">Save growth plan ↗</button><span id="plan-edit-state" class="muted">${p?'Saved locally':'Ready to draft'}</span></div></form>
 <div class="planner-result">${p ? planResult(p,fileUrl) : `<div class="plan-placeholder"><span class="eyebrow">A focused starting point</span><strong>$100</strong><p>Leads · 7 days · Meta</p><p>Save to calculate the exact budget and see the evidence behind each recommendation.</p><p class="muted">Organic work carries $0 media spend. No ad account or payment is needed.</p></div>`}</div></div>
 ${p?`<div class="plan-sections">${p.sections.map((s,index)=>`<details class="fold" ${['ORGANIC SEO','CREATIVE BRIEF'].includes(s.title)?'open':''}><summary><span>${String(index+1).padStart(2,'0')}</span> ${esc(s.title)}</summary>${s.recommendations.map(r=>`<article class="plan-recommendation">${badge(r.label)}<p>${esc(r.text)}</p>${r.sourceIds.length?`<small>Sources: ${r.sourceIds.map(id=>`<a href="#source-${id}">${esc(id)}</a>`).join(' · ')}</small>`:''}</article>`).join('')}</details>`).join('')}</div><details class="fold" id="plan-sources"><summary>OFFICIAL SOURCES & planner policy · ${p.sources.length} referenced records</summary><p>Snapshot guidance with retrieval dates and access limits. Only these referenced records enter this plan’s export.</p>${p.sources.map(s=>`<article id="source-${s.sourceId}" class="plan-source">${badge(s.type==='LAUNCHFORGE_HEURISTIC'?'PLANNER_HEURISTIC':s.type==='AVAILABILITY_BOUNDARY'?'UNKNOWN':'OFFICIAL_GUIDANCE')}<h4>${esc(s.vendor)} · ${esc(s.title)}</h4>${s.url.startsWith('https://')?`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.url)}</a>`:esc(s.url)}<p>${esc(s.rule)}</p><small>Retrieved ${esc(s.retrievedAt)} · ${esc(s.access)}<br>${esc(s.limitations)}</small></article>`).join('')}</details>`:''}`;
}
function planResult(p,fileUrl){const b=p.budget;return `<div class="plan-budget"><div class="eyebrow">Your spending envelope · USD</div><strong>${cash(b.totalCents)}</strong><p>${p.input.days} days · ${esc(p.input.goal.replaceAll('_',' '))}</p>${badge('PLANNER_HEURISTIC')}<dl><div><dt>${esc(names[b.primaryChannel]||b.primaryChannel)} primary</dt><dd>${cash(b.primaryCents)}</dd></div><div><dt>Retargeting</dt><dd>${cash(b.retargetingCents)}</dd></div><div><dt>Unspent reserve</dt><dd>${cash(b.reserveCents)}</dd></div><div><dt>Paid daily average</dt><dd>${cash(Math.round(b.averageDailyCents))}</dd></div></dl><p>${b.campaignCount} paid campaign · ${b.creativeCount} draft angles<br>Review days ${b.checkpoints.join(', ')} · organic media $0</p><p class="muted">A planning envelope, not a platform spending control or a performance forecast.</p></div>${p.warnings.map(w=>`<p class="plan-warning">${esc(w.replaceAll('_',' '))}</p>`).join('')}<div class="plan-next"><h3>Bring the plan into Campaign.</h3><p>Seeds three distinct copy angles into Grow’s existing layouts. Review claims and asset rights before rendering.</p><button id="seed-plan" type="button" class="primary">Seed creative brief ↗</button><div class="button-row"><a href="${fileUrl('growth-plan/growth-plan.md')}" download>Plan Markdown ↓</a><a href="${fileUrl('growth-plan/growth-plan.json')}" download>Plan JSON ↓</a></div></div>`;}
export function bindGrowthPlan(act,onSeed){
 const form=document.querySelector('#growth-plan-form');if(!form)return;
 form.addEventListener('input',()=>{document.querySelector('#plan-edit-state').textContent='Unsaved changes · save before seeding';const seed=document.querySelector('#seed-plan');if(seed)seed.disabled=true;});
 form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));for(const key of ['totalBudget','days','averageOrderValue','leadValue','conversionRate','contributionMargin'])data[key]=data[key]===''?null:Number(data[key]);data.currency='USD';data.retargetingRequested=form.retargetingRequested.checked;act('growth-plan',data,'Calculating and saving your growth plan…');};
 const seed=document.querySelector('#seed-plan');if(seed)seed.onclick=onSeed;
}
