import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,realpath,writeFile,mkdir,symlink,readFile,rm,truncate} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import sharp from 'sharp';
import {directPack,validatePack,loadPack,installPack,reviewPack,exportPack,seedInputs} from '../src/intake/index.js';
import {createStore} from '../src/core/store.js';
import {createApp} from '../src/server.js';
import {preflight,validateSelection,expectedTracking,preflightBinding} from '../src/preflight/index.js';
const input=()=>({identity:{name:'Cedar Bakery',audience:'Neighbors',geography:'Portland',language:'English'},claims:[{id:'menu',text:'Explore our seasonal cake menu',status:'USER_SUPPLIED',provenance:'Owned menu, reviewed 2026-10-03'},{id:'unsupported',text:'Guaranteed to double your revenue',status:'UNSUPPORTED',provenance:''}],cta:{label:'Explore menu',destination:'https://example.com/menu?flavor=lemon',utm:{source:'organic',medium:'social',campaign:'cedar-fall'}},brand:{color:'#caff68',style:'Warm editorial'},article:'# Our seasonal menu\n\nOwned draft requiring review.',rightsNotes:'Owned synthetic fixture',localAssets:[]});
async function fixture(fn){const root=await realpath(await mkdtemp(path.join(tmpdir(),'grow-r6-')));try{const asset=path.join(root,'cake.png');await sharp({create:{width:320,height:240,channels:3,background:'#e2bd76'}}).png().toFile(asset);const data=input();data.localAssets=[{file:asset,altText:'A gold product sample',rights:'Owned fixture',provenance:'Generated geometric test image'}];await fn({root,asset,data});}finally{await rm(root,{recursive:true,force:true});}}
test('owned inputs create without audit/budget; round trip resets review and retains relative asset metadata',()=>fixture(async({root,data})=>{
 const store=createStore(path.join(root,'projects')),p=await store.create({name:'Cedar',planOnly:true}),dir=store.projectDir(p.id);
 await installPack(p,dir,await directPack(data));await assert.rejects(seedInputs(p,dir),/Review/);await reviewPack(p,dir,p.productPack.revision);await seedInputs(p,dir);
 assert.equal(p.audit,null);assert.equal(p.growthPlan,undefined);assert.equal(p.campaign.variants.length,3);assert.ok(!JSON.stringify(p.campaign).includes('double your revenue'));assert.deepEqual(p.campaign.provenance.excludedClaimIds,['unsupported']);
 await exportPack(p,dir);const round=await loadPack(p.packExport.path);assert.equal(round.pack.revision,p.productPack.revision);assert.equal(round.pack.assets[0].duration,null);assert.equal(round.pack.reviewHistory.length,1);
 const q=await store.create({name:'Recipient',planOnly:true});await installPack(q,store.projectDir(q.id),round,true);assert.equal(q.productPack.review,null);await assert.rejects(seedInputs(q,store.projectDir(q.id)),/Review/);await store.save(p);assert.deepEqual((await store.get(p.id)).productPack,p.productPack);
}));
test('claim, asset and destination changes invalidate outputs and preserve historical export status',()=>fixture(async({root,asset,data})=>{
 const store=createStore(path.join(root,'projects')),p=await store.create({planOnly:true}),dir=store.projectDir(p.id);await installPack(p,dir,await directPack(data));await reviewPack(p,dir,p.productPack.revision);await seedInputs(p,dir);const old=p.productPack.revision;p.render={status:'RENDERED'};p.preflight={status:'REVIEW'};p.exports=[{status:'EXPORTED',publishedAt:null}];data.claims[0].text='Explore our reviewed cake menu';data.cta.destination='https://example.com/new';await sharp({create:{width:320,height:240,channels:3,background:'#223344'}}).png().toFile(asset);
 await installPack(p,dir,await directPack(data));assert.notEqual(p.productPack.revision,old);assert.equal(p.campaign.stale,true);assert.equal(p.render.stale,true);assert.equal(p.preflight.stale,true);assert.equal(p.exports[0].stale,true);assert.equal(p.exports[0].status,'EXPORTED');assert.equal(p.exports[0].publishedAt,null);assert.equal(p.productPack.review,null);assert.equal(p.inputHistory.length,1);
}));
test('hostile paths, forbidden fields, missing/hash/type/dimension mismatches, symlinks and oversized files fail closed',()=>fixture(async({root,data,asset})=>{
 const {pack}=await directPack(data),folder=path.join(root,'pack');await mkdir(path.join(folder,'assets'),{recursive:true});const jsonFile=path.join(folder,'product-brand-pack.json');await writeFile(path.join(folder,pack.assets[0].path),await readFile(asset));await writeFile(jsonFile,JSON.stringify(pack));assert.equal((await loadPack(jsonFile)).pack.revision,pack.revision);const save=async c=>{delete c.revision;await writeFile(jsonFile,JSON.stringify(c));};
 for(const bad of ['../escape.png','/tmp/x.png','assets/../escape.png','assets/x;touch.png','assets/x\\y.png']){const c=structuredClone(pack);c.assets[0].path=bad;delete c.revision;assert.throws(()=>validatePack(c),/path/i);}
 for(const key of ['scripts','credentials','providerToken','publishApproval','__proto__']){const c=JSON.parse(JSON.stringify(pack));Object.defineProperty(c,key,{value:'forbidden',enumerable:true});assert.throws(()=>validatePack(c),/fields/);}
 const missing=structuredClone(pack);missing.assets[0].path='assets/missing.png';await save(missing);await assert.rejects(loadPack(jsonFile),/ENOENT/);
 for(const [key,value] of [['sha256','0'.repeat(64)],['mime','image/jpeg'],['width',200],['bytes',1]]){const c=structuredClone(pack);c.assets[0][key]=value;await save(c);await assert.rejects(loadPack(jsonFile),/mismatch/);}
 const c=structuredClone(pack);c.assets[0].path='assets/link.png';await symlink(asset,path.join(folder,'assets','link.png'));await save(c);await assert.rejects(loadPack(jsonFile),/Symlinks/);await symlink(folder,path.join(root,'linked-folder'));await assert.rejects(loadPack(path.join(root,'linked-folder','product-brand-pack.json')),/Symlinks/);
 const huge=path.join(root,'large.json');await writeFile(huge,'{}');await truncate(huge,128*1024+1);await assert.rejects(loadPack(huge),/bounded/);const big=path.join(root,'large.png');await writeFile(big,'x');await truncate(big,10*1024*1024+1);data.localAssets[0].file=big;await assert.rejects(directPack(data),/bounded/);
}));
test('unsupported-only claims never seed; copied review cannot grant authority',()=>fixture(async({root,data})=>{
 data.claims=data.claims.filter(c=>c.status==='UNSUPPORTED');const store=createStore(path.join(root,'projects')),p=await store.create({planOnly:true}),dir=store.projectDir(p.id);await installPack(p,dir,await directPack(data));await assert.rejects(reviewPack(p,dir,'0'.repeat(64)),/changed/);await reviewPack(p,dir,p.productPack.revision);await assert.rejects(seedInputs(p,dir),/Unsupported/);
}));
test('selection validates; preflight exposes exact CTA/destination/UTM issues and platform rules stay UNKNOWN',()=>fixture(async({root,data})=>{
 const store=createStore(path.join(root,'projects')),p=await store.create({planOnly:true}),dir=store.projectDir(p.id);await installPack(p,dir,await directPack(data));await reviewPack(p,dir,p.productPack.revision);await seedInputs(p,dir);p.campaign.confirmed=true;assert.throws(()=>validateSelection({concept:'other'},p),/concept/);assert.throws(()=>validateSelection({concept:'spotlight',ratios:['square','square']},p),/ratios/);
 p.selection=validateSelection({concept:'editorial',ratios:['square','story'],trackedUrl:'https://wrong.example/',altText:'Gold sample and menu copy',reviewed:true},p);p.campaign.variants[1].cta='Wrong CTA';p.campaign.url='https://example.com/wrong';const f=await preflight(p);assert.ok(f.blockers.some(v=>v.includes('CTA mismatch')));assert.ok(f.blockers.some(v=>v.includes('Destination mismatch')));assert.ok(f.blockers.some(v=>v.includes('Destination/UTM mismatch')));assert.equal(f.platformRules.status,'UNKNOWN');assert.ok(f.ratios.every(r=>r.platformRule==='UNKNOWN'));assert.equal(f.localExportReady,false);assert.ok(expectedTracking(p,'editorial').includes('flavor=lemon'));assert.ok(expectedTracking(p,'editorial').includes('utm_content=editorial'));const before=preflightBinding(p);p.selection.altText='Changed description';assert.notEqual(preflightBinding(p),before);
}));
test('API rejected imports preserve project bytes; changed reviewed asset invalidates render attempt',()=>fixture(async({root,data})=>{
 const app=createApp({dataDir:path.join(root,'data')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${app.server.address().port}`;const post=async(route,input)=>{const r=await fetch(origin+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});return {status:r.status,p:await r.json()};};try{let {p}=await post('/api/projects',{planOnly:true});const route='/api/projects/'+p.id;p=(await post(route+'/product-inputs',data)).p;const file=path.join(app.store.projectDir(p.id),'grow.project.json'),before=await readFile(file);assert.equal((await post(route+'/import-product-pack',{file:path.join(root,'missing.json')})).status,400);assert.deepEqual(await readFile(file),before);p=(await post(route+'/review-product-pack',{confirmed:true,revision:p.productPack.revision})).p;p=(await post(route+'/seed-inputs',{})).p;p=(await post(route+'/campaign',{confirmed:true})).p;await writeFile(path.join(app.store.projectDir(p.id),p.productPack.root,p.productPack.assets[0].path),'tampered');assert.equal((await post(route+'/render',{})).status,400);p=await app.store.get(p.id);assert.equal(p.campaign.stale,true);assert.equal(p.productPack.review,null);assert.equal(p.productPack.status,'STALE');}finally{app.server.closeAllConnections();await new Promise(r=>app.server.close(r));}
}));
