import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {importQueryCsv} from '../../src/evidence/import/index.js';import {freezePlan,observeResults,compareResults,reviewAdjustment} from '../../src/measurement/workspace.js';
const plan=JSON.parse(await readFile(new URL('../campaign-learning-r7c/r5-plan.json',import.meta.url)));
const cohort={id:'test',source:'manual',report:'campaign total',attribution:'7 day click',filters:'all'};
const metadata={sourceName:'Synthetic results',importedAt:'2026-10-03T00:00:00Z',observedWindow:{start:'2026-09-01',end:'2026-09-30',timezone:'UTC'},cohort,accountScope:'fixture',geography:'US',currency:'USD'};
const metrics={paidSpendCents:{column:'spend',unit:'currency'},revenueCents:{column:'revenue',unit:'currency'},impressions:{column:'impressions',unit:'count'},clicks:{column:'clicks',unit:'count'},conversions:{column:'conversions',unit:'count'}};
test('normalized result -> immutable snapshot comparison -> reviewed allocation preserves cents and history',()=>{let p={id:'campaign-1',growthPlan:plan};freezePlan(p,{reviewed:true,start:'2026-09-01',end:'2026-09-30',cohort,account:'fixture',geography:'US'});const snapshot=p.learning.snapshots[0],frozen=JSON.stringify(snapshot);const normalized=importQueryCsv('query,spend,revenue,impressions,clicks,conversions\nTotal,80.00,120.00,1000,50,2.5\n',{metadata,mapping:{queryColumn:'query',metrics}});p.evidenceImports=[{id:normalized.importId,normalized}];observeResults(p,{snapshotId:snapshot.snapshotId,importId:normalized.importId,rowId:normalized.rows[0].rowId,reviewed:true,coverage:'COMPLETE'});assert.equal(p.learning.observations[0].actual.paidSpendCents,8000);assert.equal(p.learning.observations[0].actual.conversions,'2.5');const originalObservation=JSON.stringify(p.learning.observations);compareResults(p,{snapshotId:snapshot.snapshotId,observationIds:p.learning.observations.map(o=>o.observationId),adjustment:{primaryCents:1000,retargetingCents:0,reserveCents:1000,explanation:'Preserve reserve; reviewed remaining envelope only.'}});assert.equal(p.learning.comparison.comparable,true);assert.equal(p.learning.comparison.deltas.budget.unspentEnvelopeCents,2000);reviewAdjustment(p,{proposalId:p.learning.comparison.proposedAdjustment.proposalId,reviewed:true});assert.equal(p.learning.proposalReviews[0].execution,'NONE');p.growthPlan={...plan,revision:'new-plan'};p=JSON.parse(JSON.stringify(p));assert.equal(JSON.stringify(p.learning.snapshots[0]),frozen);assert.equal(JSON.stringify(p.learning.observations),originalObservation);assert.throws(()=>observeResults(p,{snapshotId:snapshot.snapshotId,importId:normalized.importId,rowId:normalized.rows[0].rowId,reviewed:true,coverage:'COMPLETE'}),/already/);});
test('integration refuses unknown cohort identity instead of calling matching placeholders comparable',()=>{
 for(const field of ['id','source','report','attribution']){const p={id:'campaign-unknown',growthPlan:plan};assert.throws(()=>freezePlan(p,{reviewed:true,start:'2026-09-01',end:'2026-09-30',cohort:{...cohort,[field]:'UNKNOWN'},account:'fixture',geography:'US'}),/explicit|known/i);assert.equal(p.learning,undefined);}
});
